### ISSUE TITLE
Make beeDebug url optional for contructor

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-storage#103]
At the moment, this link is only used to obtain a stamp. We can get rid of this feature (or move it to utilities), then it will be possible for fdp-storage to work with swarm gateways.

This param could be replaced by parameters with specific stamps.

**Comment by crtahlin** [comment]
@nugaon please decide on path and priority.

**Comment by crtahlin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fdp-storage/103?planning-poker) with ZenHub @nugaon

**Comment by nugaon** [comment]
I think first, we could just extend the type and the handling of this 2nd debug url parameter with the possibility to provide postage stamp as you described in order to not introduce breaking change.

The debug API URL eventually will be ruled out of the Bee client sooner or later anyway when the restricted API will be on default. (speaking of that, we should need to support that feature as well as it is already available in Bee. Please create a ticket about it after you checked that out). 

IMO it is on mid priority
