### ISSUE TITLE
Error: "User account already uploaded" on account imported using a mnemonic phrase.

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fdp-storage#199]
Is there a method to check if an imported (using mnemonic phrase) wallet account has already been registered on-chain or not? 
For example to show a "Register" button only if the account isnt portable yet.

**Comment by rampall** [comment]
Related: Is it possible to get the registered username from AccountData class?

**Comment by crtahlin** [comment]
@nugaon please triage.

**Comment by nugaon** [comment]
You can check whether the imported wallet is registered already with a given username by the `fdp.account.isPublicKeyEqual(username)` method.

It is detailed in the README section.

> Related: Is it possible to get the registered username from AccountData class?

No, it is not possible currently since we do not have reverse lookup registrar contract.
If you have such needs please create a ticket in [FDP Contracts](https://github.com/fairDataSociety/fdp-contracts) but the ENS was used for only portable accounts feature so far that does not require reverse lookup.
